# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeTest
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya', '~> 15.0'
  pod 'Kingfisher'
end
